### ISSUE TITLE
Problem connecting to IP

### ISSUE THREAD

**Issue by Evanito** [artemperl/plb-widget#1]
I attempted to connect to a local IP in the form `192.168.1.103:8000/botlog.json`. And at first I got a long loading screen until it eventually loaded, and now the widget only displays zero values.

Earlier, I was receiving an immediate error about connecting to the address.

In addition, I am unable to click on the little settings cog (or if I am hitting it, nothing is popping up.)

I am using Android 7.0 unrooted, with the Google homescreen, and the precompiled release of the apk.

**Comment by artemperl** [comment]
Hi Evan, thanks for reporting the issue. I couldn't reproduce the problem, it works without errors on my device even when connecting to an IP address in the local network.
The non-reacting settings button is probably just another symptom of the same issue.
Is your web browser on your device able to connect to the same path and does it display the botlog?

I will probably include an option to display an error log in the upcoming version to help me with such issues.

**Comment by Evanito** [comment]
Yes, I tested it by copy-pasting the same IP to both the browser and the app. The botlog was correctly returned in the browser.

If it is relevant, I have a VPN app on my phone that I occasionally use but was disabled at the time.

**Comment by Evanito** [comment]
Attached are relevant photos:

Log when checked through browser:
https://drive.google.com/open?id=0By47wOGzjnn_anFqMENyZGJ4Nzg

When attempting to connect to same IP as above via widget:
https://drive.google.com/open?id=0By47wOGzjnn_YjZWUkJ5VVd6Qlk
(Same result when not prefaced with http://)

**Comment by artemperl** [comment]
I just uploaded the new version, which includes an error log. Could you update to the [newest version](https://github.com/artemperl/plb-widget/releases/tag/v1.0.1) and post the error log after trying to connect again?  
You can find the error log in the menu at the top right corner of the configuration screen.

**Comment by Evanito** [comment]
```
Sun Jun 04 17:04:23 MST 2017
com.google.gson.JsonSyntaxException: duplicate key: null
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:190)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.artem.lendingwidget.network.LendingNetworkService.handleActionBotlog(LendingNetworkService.kt:130)
	at com.artem.lendingwidget.network.LendingNetworkService.onHandleIntent(LendingNetworkService.kt:43)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by Evanito** [comment]
This one should be more useful, get this after 30s+ of loading icon:
```
Sun Jun 04 17:07:17 MST 2017
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
	at java.net.Socket.connect(Socket.java:586)
	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
	at com.android.okhttp.Connection.connectSocket(Connection.java:1432)
	at com.android.okhttp.Connection.connect(Connection.java:1390)
	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1667)
	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:133)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:466)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:371)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:503)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:438)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:247)
	at java.net.URL.openStream(URL.java:1058)
	at com.artem.lendingwidget.network.LendingNetworkService.handleActionBotlog(LendingNetworkService.kt:53)
	at com.artem.lendingwidget.network.LendingNetworkService.onHandleIntent(LendingNetworkService.kt:43)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by Evanito** [comment]
I tested it with a static, remote IP and got the same error.

**Comment by artemperl** [comment]
The  [newest release](https://github.com/artemperl/plb-widget/releases/tag/v1.0.1a) fixes the issue.  
  
The problem was that cryptocurrencies were implemented as enum constants. I haven't included all cryptocurrencies though, therefore the json converter mapped unknown currencies to null values, which caused problems. Cryptocurrencies are treated as strings now so this shouldn't cause any more problems.  
Let me know if any other issues occur.

**Comment by Evanito** [comment]
Very cool, thanks for the fix!
Are you in the Slack channel? I would like to discuss something with you.

**Comment by artemperl** [comment]
Just joined the channel :)
